package com.mx5dash.obd2android.storage

import android.content.ContentResolver
import android.content.Context
import android.net.Uri
import android.util.Log
import java.io.File
import java.io.IOException
import java.io.OutputStream

object IniExporter {

    private const val TAG = "IniExporter"

    fun generateIniText(prefs: PreferencesManager): String {
        val sb = StringBuilder()
        sb.append("# MX-5 Dash System Preferences Configuration\n")
        sb.append("# Generated by OBD2Android - 100% Byte-Compatible with ESP32-S3 SD Importer\n\n")

        sb.append("[DISPLAY]\n")
        sb.append("rotation=").append(prefs.rotation).append("\n")
        sb.append("units_us=").append(if (prefs.unitsUs) "1" else "0").append("\n")
        sb.append("theme_mode=").append(prefs.themeMode).append("\n")
        sb.append("brightness_pct=").append(prefs.brightness).append("\n\n")

        sb.append("[LOGGING]\n")
        sb.append("auto_incident=").append(if (prefs.autoLog) "1" else "0").append("\n")
        sb.append("speed_mask=").append(if (prefs.speedMask) "1" else "0").append("\n\n")

        sb.append("[COMMUNICATION]\n")
        sb.append("ble_prefix=").append(prefs.blePrefix).append("\n\n")

        sb.append("[TPMS]\n")
        sb.append("fl_did=").append(prefs.getWheelDid(0)).append("\n")
        sb.append("fr_did=").append(prefs.getWheelDid(1)).append("\n")
        sb.append("rl_did=").append(prefs.getWheelDid(2)).append("\n")
        sb.append("rr_did=").append(prefs.getWheelDid(3)).append("\n")

        return sb.toString()
    }

    fun exportToUri(resolver: ContentResolver, uri: Uri, prefs: PreferencesManager): Boolean {
        val content = generateIniText(prefs)
        return try {
            resolver.openOutputStream(uri, "wt")?.use { os: OutputStream ->
                os.write(content.toByteArray(Charsets.UTF_8))
                os.flush()
            } ?: throw IOException("Failed opening URI OutputStream")
            Log.i(TAG, "Successfully exported sys_prefs.ini to URI")
            true
        } catch (e: Exception) {
            Log.e(TAG, "Failed exporting sys_prefs.ini via SAF", e)
            false
        }
    }

    fun exportToLocalFile(path: File, prefs: PreferencesManager): Boolean {
        val content = generateIniText(prefs)
        return try {
            path.parentFile?.mkdirs()
            path.writeText(content, Charsets.UTF_8)
            Log.i(TAG, "Successfully saved sys_prefs.ini to ${path.absolutePath}")
            true
        } catch (e: Exception) {
            Log.e(TAG, "Failed saving local sys_prefs.ini", e)
            false
        }
    }
}
